name: reacher
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^12.3.4
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  audioplayers: ^6.1.0

  speech_to_text: ^7.0.0  # Check for the latest version
  permission_handler: ^10.0.0
  flutter_svg: ^1.0.3
  gif: ^2.3.0
  fl_chart: ^0.69.2
  url_launcher: ^6.1.5
  flutter_pdfview: ^1.3.4 # Add this line
  syncfusion_flutter_pdfviewer: ^27.2.3
  video_player: ^2.9.2
  flutter_pptx: ^0.1.3
  webview_flutter: ^4.10.0




  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true


  assets:
      - assets/images/
      - assets/sounds/
      - assets/videos/
      - assets/videos/abc.mp4
